apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-clinic-deployment
  labels:
    app: pet-clinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pet-clinic
  template:
    metadata:
      labels:
        app: pet-clinic 
    spec:
      containers:
      - name: pet-clinic
        image: bravinwasike/react-app:latest   # edit this
        ports:
        - containerPort: 3000