apiVersion: v1
kind: PersistentVolume
metadata:
  name: maven-repo-pv-nhatnd19
  namespace: agent-nhatnd19
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    path: /shares/.m2
    server: 10.98.218.203
