apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-repo-pvc-nhatnd19
  namespace: agent-nhatnd19
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
