apiVersion: v1
kind: Service
metadata:
  name: pet-clinic-service 
spec:
  selector:
    app: pet-clinic
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000 #Service port
    targetPort: 3000 #The port for the React.js application container